function Hd = kaiser_filter
%KAISER_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 17-Oct-2015 11:01:20

% FIR Window Highpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 20000;  % Sampling Frequency

Fstop = 600;             % Stopband Frequency
Fpass = 850;             % Passband Frequency
Dstop = 0.031622776602;  % Stopband Attenuation
Dpass = 0.057501127785;  % Passband Ripple
flag  = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop Fpass]/(Fs/2), [0 1], [Dpass Dstop]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

% [EOF]
